### ISSUE TITLE
Looks blurry on Retina screens

### ISSUE THREAD

**Issue by Blackslash333** [maierfelix/poxi#4]
Hey,

Thats a really nice tool that you got there. Just one little thing to add is a CSS property on the canvas element to make it look like more "pixelated" than "blurry" on retina screens.

Just change your image-rendering property value by "pixelated".

`image-rendering: pixelated;`

Nice work tho, keep going.

**Comment by maierfelix** [comment]
I have updated the latest demo branch, could you check if the issue still exists? Make sure to clear the browser's cache if it doesn't work

**Comment by Blackslash333** [comment]
All good here. Good work !
