### ISSUE TITLE
New cursor

### ISSUE THREAD

**Issue by Blackslash333** [maierfelix/poxi#5]
With canvas you should be able to create & use a custom cursor. At the moment I think that the "pointer" cursor is pretty ugly and is taking too much place while making pixel art. The cursor should be a pencil or something thin like this.

**Comment by maierfelix** [comment]
That's a good point, could you search for some free available icon sets I can add to here?

**Comment by Blackslash333** [comment]
Sure, something like this : https://www.iconfinder.com/icons/1167983/draw_drawing_edit_pen_pencil_write_writing_icon#size=128

**Comment by maierfelix** [comment]
Added with https://github.com/maierfelix/poxi/commit/7e5be8475d2d2fb2f3ecf36aed485bdc205a49f3
